steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'install']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['image', 'rm' , '-f', 'maniavision/backend-employee']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'maniavision/backend-employee', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'maniavision/backend-employee', 'us-central1-docker.pkg.dev/gcp-101-405620/emp-app/employee-app']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/gcp-101-405620/emp-app/employee-app']
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['login', '-u', 'maniavision', '-p', 'Fort12632142']
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', 'maniavision/backend-employee']
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['image', 'ls']
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['run', 'deploy', 'backend-employee', '--image', 'maniavision/backend-employee:latest', '--region=us-central1', '--allow-unauthenticated']
options:
  logging: CLOUD_LOGGING_ONLY
